### ISSUE TITLE
Deepin Store does not work when using system proxy

### ISSUE THREAD

**Issue by Velociround** [linuxdeepin/deepin-appstore#1]
I'm using Deepin 15 at work. Everyone needs to use this proxy to work here. The internet simply does not work at all without the proxy.
![deepinscreenshot20160224114144](https://cloud.githubusercontent.com/assets/816290/13288632/9a76641e-daeb-11e5-8ed1-daa181020ada.png)

I have set the proxy settings globally on the system, but Deepin Store does not seem to use them.
![deepinscreenshot20160224113323](https://cloud.githubusercontent.com/assets/816290/13288394/7a630368-daea-11e5-82c0-74c9f109acab.png)

I also needed to override Firefox proxy settings to make Firefox work with the proxy. Simply using system defined proxy didn't work.
![deepinscreenshot20160224113744](https://cloud.githubusercontent.com/assets/816290/13288520/0c6d6834-daeb-11e5-85b8-f4c15b04d92e.png)

Is there a way to fix the system proxy settings or override proxy settings in Deepin Store to make it work? I tried `$ deepin-appstore --help` but it there's no option to override the proxy settings.

Thank you in advance.

**Comment by snyh** [comment]
@Xinkai   Does deepin-appstore (or qt ) support http_proxy environments ?   

Control Center will set this environments.  @fasheng

**Comment by Xinkai** [comment]
It seems that Qt doesn't read the related environment variables. However it should be a fairly easy feature to add.

**Comment by snyh** [comment]
Just use http://doc.qt.io/qt-5/qnetworkproxyfactory.html#setUseSystemConfiguration  this ? 

@Xinkai Can you submit a CL , so @Velociround  can help testing in his work environment.

**Comment by fasheng** [comment]
I am rewriting proxy module now. At first, i want to wrapper a low level net twork implementation such as iptable or some other methods, but looks it's not so easy. So we have to use the proxy envs or gsettings continue, and we'd better write it as a general Qt module so it could be append for other applications easily(the old c code in dde-workspace was dropped for a long time). 



2016年2月25日 12:01, 12:01，在 xiabin <notifications@github.com> 已写:

**Comment by Velociround** [comment]
I have more information about proxy in Deepin, maybe it helps: this problem seems to be widespread in Deepin. I could not find any app that works using the global system proxy settings.

Sometimes, when I reboot the system, one of the proxies (apparently at random, every time is a different one) changes to port 0. I always check this when I reboot, and change to the correct port.
![deepinscreenshot20160225105100](https://cloud.githubusercontent.com/assets/816290/13321431/b4224686-dbad-11e5-829d-4703792eabc0.png)
The 0 port also appears when I do `~$ echo $http_proxy` after this problem occurs.

After pressing "Apply system wide", `~$ echo $http_proxy $https_proxy $ftp_proxy` always shows the correct proxy settings.

The global proxy settings only set the lower case environments. Upper case `~$ echo $HTTP_PROXY $HTTPS_PROXY $FTP_PROXY` does not print anything.

Here's the apps I tried so far (none of them are able to connect to the internet because they are not picking up the proxy settings):
- deepin-appstore
- geary (connects to work internal mail network and shows mail but does not load any external images from internet)
- gnome-calendar (does not connect to any internet calendar)
- gnome-todo (is not able to create lists - maybe not related)
- gnome-weather (can not show weather information for any city)
- apps.com.google.map (opens a blank window because it requires internet to open the webpage)
- apps.com.pixlr (opens a blank window because it requires internet to open the webpage)
- apps.net.skyinc (opens a blank window because it requires internet to open the webpage)
- Firefox (using "system proxy" settings does not work; however, it works when I override the proxy in Firefox settings)

Blank windows from internet-only apps (all look the same):
![deepinscreenshot20160225103914](https://cloud.githubusercontent.com/assets/816290/13321154/0eee4b5c-dbac-11e5-92f7-483ec3fe6558.png)

- Google Chrome does not work at all, not even using `$ google-chrome --proxy-server=host:port`, and is not able to override proxy settings
![deepinscreenshot20160225104458](https://cloud.githubusercontent.com/assets/816290/13321295/f98869c2-dbac-11e5-9e6d-8e6596642def.png)

Is there somewhere else I should open an issue about this? Can you help me? Thank you very much

**Comment by fasheng** [comment]
Thanks for the detailed report. Someone noticed it before in our bugzilla.

Well, I must say, google-chrome works before, but it read gnome proxy gsettings like firefox in latest version. So we will sync our proxy setting to gnome to solve it this time.  Please ignore KDE, there is another implemntation for it, maybe we will support it in future...

**Comment by Velociround** [comment]
Just so you know, Deepin has just updated the deepin-appstore (and some 660MB of other packages and _Deepin patches_), but the issue remains.

![deepinscreenshot20160225144704](https://cloud.githubusercontent.com/assets/816290/13401055/5b9c2290-dee9-11e5-8c6a-8571e7811dd9.png)

I also had a lot of problems when trying to install this update; I only have 2 trustworthy mirrors: official (slow, 10KB/s) and Brazilian (fastest, 1MB/s+). The Brazilian mirror did tell me about the update but it didn't have the update files (404 Not Found for all packages when trying `~$ sudo apt-get upgrade`) so I had to update from the Control Center GUI using Official Mirror, because only this way it seemed to resume downloading the packages after failed attempts (rather than start from the beginning).

The update froze several times, requiring me to reboot the system because the GUI wouldn't tell me what the problem was and wouldn't let me stop / restart / resume either (I figured it out using apt-get to read the error messages).

Even after finishing the download ("0 bytes left"), the Control Center wouldn't let me update.
![deepinscreenshot20160229101443](https://cloud.githubusercontent.com/assets/816290/13401181/e6247c5a-dee9-11e5-8047-29cf63a96ab7.png)
![deepinscreenshot20160229101504](https://cloud.githubusercontent.com/assets/816290/13401187/eb296896-dee9-11e5-8247-1e767f7b7c7c.png)

Then, I changed the mirror to Brazilian in /etc/apt/sources.list , did `~$ sudo apt-get update` then `~$ sudo apt-get upgrade`, and it started upgrading all of the already downloaded packages (which I was very happy about, because when it showed "0/660MB downloaded" on the confirmation screen, I thought it would download it all again).

After apt-get finished upgrading all packages, Control Center still had the "Deepin patches" update left to install (even though apt-get showed "nothing to upgrade"). I tried to upgrade Deepin patches again through the GUI, and now it successfully installed.

Just to make it clear: _Deepin patches_ only upgraded after I did `~$ sudo apt-get upgrade`. It failed all previous attempts to go through with only the Control Center GUI.

I rebooted, tested the proxy again (same problem), and here I am now.

Can I / should I report bugs on your Deepin bugzilla or something? I don't know the address or anything else about it. I can't use the deepin-feedback (Feedback assistant) because I don't have working proxy settings (and failed to find specific proxy settings for it), so it simply doesn't work / doesn't send the reports.

Thank you again!

**Comment by fasheng** [comment]
Sorry for the trouble..

Yes, you could report the updating problem to bugzilla, it's the first choice in most time. But for the github users, report it as a github issue is just fine, our developers will pay attention to it, too.

Looks the problem is appstore related, so you could split your comment to another issue here :)

**Comment by fasheng** [comment]
deepin-appstore use system proxy now, please wait for the next release `4.0.8`.

BTW:  The applications that read proxy settings from environment variables require restart after proxy changed.

**Comment by Velociround** [comment]
I just got the update yesterday and I'm glad to say it works. Thank you.

A few apps still don't seem to work (e.g.: weather)

**Comment by snyh** [comment]
authentication window  for  proxy.

Oh,  it''s not seems  that easy for offering this for every application.  
But we have to think of this situation. 
@hualet @fasheng

**Comment by fasheng** [comment]
Well, if the client application(here is Qt) doesn't provide proxy auth dialog feature,  we can do very little...

**Comment by fusion809** [comment]
I still have this problem with deepin store. I haven't set any proxy, my deepin system is fairly vanilla, largely unmodified from the default. 

The only modifications I've made is I've installed a few applications and added a few files to /etc/apt/sources.list.d/ in order to install extra apps and edited /etc/apt/preferences to do some apt pinning (e.g. I wanted RuneScape's NXT Client instead of the old Java client in the deepin repos, I also wanted 0 A.D. 22nd alpha instead of the 21st which is in the deepin repos). 

I've successfully logged in to the deepin store, so at least that works. Trying to post comments fails, like I can enter the comment but when I click "Publish" it says it failed to publish it. Other than this deepin seems to be working perfectly. No issues with connecting to websites occur in my browser. I can comment on GitHub fine, so it certainly seems like the deepin store is what has the problem.

**Comment by snyh** [comment]
@fusion809 try `deepin-appstore -c` ?

**Comment by fusion809** [comment]
@snyh Crashed with https://pastebin.com/umjtphbV.

**Comment by snyh** [comment]
the warning log is about gtk2 theme configure.  

The gtk theme problem unlikely cased by deepin-appstore. 
What OS you are running?  Please paste the package list by running `dpkg -l` or correspondent command if you aren't under debian.

`deepin-appstore -c` just clean the cache. After the clean. You should run deepin-appstore normally.

**Comment by snyh** [comment]
It should be ok now.  The problem is in appstore's server.

**Comment by fusion809** [comment]
Ah yes it's working now, thanks.
