### ISSUE TITLE
No search results found

### ISSUE THREAD

**Issue by doggolabs** [linuxdeepin/deepin-appstore#106]
Hi, 
It does not matter what I type into the search bar, there are no reuslts found.

Example: Libre Office which is supported by the store and on the first page.
I'm not logged in to the store and installing software from the store works.

Store version: 5.3.1.0
Deepin 15.11 Desktop

![DeepinScreenshot_dde-desktop_20190819210955](https://user-images.githubusercontent.com/54288127/63292514-1f8a9600-c2c6-11e9-8380-e81154cdc613.png)

**Comment by NjlsShade** [comment]
This was happening to me as well for a few weeks, however, has since resolved itself after an update to Deepin Store 5.3.1.2.

Are you still seeing the issue present after updating, @Doggolabs-Marcus?

**Comment by doggolabs** [comment]
For now this issue is resolved, just yesterday I used the store and the search worked even with autocomplete! So it works with 5.3.1.2.
