### ISSUE TITLE
ubuntu18.04 环境下编译失败

### ISSUE THREAD

**Issue by chuntsky** [linuxdeepin/deepin-appstore#11]
dpkg-buildpackage: info: 源码包 deepin-appstore
dpkg-buildpackage: info: 源码版本 4.0.9.7-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: 源码修改者 Iceyer <me@iceyer.net>
dpkg-buildpackage: info: 主机架构 amd64
 dpkg-source --before-build deepin-appstore
 debian/rules clean
dh clean
   debian/rules override_dh_auto_clean
make[1]: 进入目录“/home/land/soft/deepin-appstore”
dh_auto_clean --
	rm -rf obj-x86_64-linux-gnu
rm -fr build
make[1]: 离开目录“/home/land/soft/deepin-appstore”
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f debian/deepin-appstore-data.debhelper.log debian/deepin-appstore.debhelper.log
	rm -f -- debian/deepin-appstore.substvars debian/deepin-appstore-data.substvars debian/files
	rm -fr -- debian/deepin-appstore/ debian/tmp/ debian/deepin-appstore-data/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source -b deepin-appstore
dpkg-source: 警告: native package version may not have a revision
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building deepin-appstore in deepin-appstore_4.0.9.7-1.tar.xz
dpkg-source: info: building deepin-appstore in deepin-appstore_4.0.9.7-1.dsc
 debian/rules build

[ 28%] Building CXX object CMakeFiles/deepin-appstore.dir/FilterMouseMove.cpp.o
/usr/bin/c++  -DBUILD_WITH_WEBKIT=1 -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DSHELL_VERSION=\"4.0.9\" -I/home/land/soft/deepin-appstore/obj-x86_64-linux-gnu -I/home/land/soft/deepin-appstore -I/home/land/soft/deepin-appstore/obj-x86_64-linux-gnu/deepin-appstore_autogen/include -I/usr/include/libdtk-2.0.7/DWidget -I/usr/include/libdtk-2.0.7/DCore -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit  -g -O2 -fdebug-prefix-map=/home/land/soft/deepin-appstore=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Werror   -D USE_OPAQUE_REGION_OPTIMIZATION=0 -fPIC -std=gnu++11 -o CMakeFiles/deepin-appstore.dir/FilterMouseMove.cpp.o -c /home/land/soft/deepin-appstore/FilterMouseMove.cpp
/home/land/soft/deepin-appstore/FilterMouseMove.cpp: In member function ‘virtual bool FilterMouseMove::eventFilter(QObject*, QEvent*)’:
/home/land/soft/deepin-appstore/FilterMouseMove.cpp:34:57: error: this statement may fall through [-Werror=implicit-fallthrough=]
             static_cast<Shell*>(qApp)->setTooltipVisible(false);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/land/soft/deepin-appstore/FilterMouseMove.cpp:37:9: note: here
         case QEvent::Enter: {
         ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/deepin-appstore.dir/build.make:161: recipe for target 'CMakeFiles/deepin-appstore.dir/FilterMouseMove.cpp.o' failed
make[4]: *** [CMakeFiles/deepin-appstore.dir/FilterMouseMove.cpp.o] Error 1
make[4]: 离开目录“/home/land/soft/deepin-appstore/obj-x86_64-linux-gnu”
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/deepin-appstore.dir/all' failed
make[3]: *** [CMakeFiles/deepin-appstore.dir/all] Error 2
make[3]: 离开目录“/home/land/soft/deepin-appstore/obj-x86_64-linux-gnu”
Makefile:132: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: 离开目录“/home/land/soft/deepin-appstore/obj-x86_64-linux-gnu”
dh_auto_build: cd obj-x86_64-linux-gnu && make -j1 returned exit code 2
debian/rules:9: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: 离开目录“/home/land/soft/deepin-appstore”
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: 错误: debian/rules build subprocess returned exit status 2

**Comment by cybersmurf** [comment]
I have same problem. Any solutions?

**Comment by Iceyer** [comment]
it fix now. but we do not maintain 4.x.x version now，we release 5.x.x.

**Comment by Iceyer** [comment]
by the way, this because you build source with treated warning as error, just adjust you build flags or add a `break` if necessary.

```
/home/land/soft/deepin-appstore/FilterMouseMove.cpp:34:57: error: this statement may fall through [-Werror=implicit-fallthrough=]
static_cast<Shell*>(qApp)->setTooltipVisible(false);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/land/soft/deepin-appstore/FilterMouseMove.cpp:37:9: note: here
case QEvent::Enter: {
^~~~
cc1plus: all warnings being treated as errors
```
and if fixed by:
https://github.com/linuxdeepin/deepin-appstore/commit/ceac5cd20c259f4b86c006c4909a14a6ab070f2b
