### ISSUE TITLE
Latest new feature release ... reported instability ... fixed ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-appstore#13]
Hi,

as per the comments to your facebook post on this exciting new release of deepin-appstore there seems to be some big issues as per early users.

Have these been addressed/fixed ? Just want to know if i can go ahead and install it ?

I have held on from installing after reading the initial feedback found on this post.

[Facebook Post](https://www.facebook.com/deepinlinux/posts/2154303251249741)

**Comment by Iceyer** [comment]
Now deepin store has release 5.2.0.6-1, most issue has fixed and you can enjoy it.
