### ISSUE TITLE
Only display installed app in the store 

### ISSUE THREAD

**Issue by saileshkush95** [linuxdeepin/deepin-appstore#20]
After updating Deepin OS using `sudo apt dist-upgrade` command it only display installed apps on my system. As below in the picture.
![deepinscreenshot_20181213233348](https://user-images.githubusercontent.com/28560875/49957327-90a3cd80-ff2f-11e8-8734-ec8acec4a1a2.png)
Please help me as soon as possible..
Thanks for this amazing os

**Comment by Iceyer** [comment]
Please provide this command output:

```
apt-cache policy deepin-appstore
cat /usr/share/deepin-appstore/settings.ini.*
```

**Comment by saileshkush95** [comment]
Here is the outpu
![DeepinScreenshot_deepin-terminal_20190412214349](https://user-images.githubusercontent.com/28560875/56050845-ad7cd000-5d6c-11e9-81d5-122143e48593.png)
![DeepinScreenshot_deepin-terminal_20190412214306](https://user-images.githubusercontent.com/28560875/56050846-ad7cd000-5d6c-11e9-9d4e-e53c30a2a5bc.png)

**Comment by Iceyer** [comment]
pllesase check is if `/etc/apt/sources.list` is valid by 

```
┌💁  iceyer @ 💻  builder in 📁  ~
└❯ cat /etc/apt/sources.list
## Generated by deepin-installer
deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
```

and then run:

```
sudo apt update
```

It seem that you lose you apt repo config...
