### ISSUE TITLE
installing APP Store on ubuntu error

### ISSUE THREAD

**Issue by Xman993** [linuxdeepin/deepin-appstore#30]
![image](https://user-images.githubusercontent.com/6819293/56079914-009d6400-5dfb-11e9-929f-214bf2e52b27.png)

When i try to install appstore i get this error

**Comment by Iceyer** [comment]
we really do not recommand you do that, but you can see here for how to install deb pkg:

https://askubuntu.com/questions/176121/dpkg-error-trying-to-overwrite-file-which-is-also-in
