### ISSUE TITLE
登录按钮点击没反应

### ISSUE THREAD

**Issue by abcfy2** [linuxdeepin/deepin-appstore#43]
系统为最新的15.10.1，所有软件包都最新。appstore点击右上角的登录按钮和下面评论区的登录都没有任何反应。

![深度录屏_deepin-appstore_20190606002533](https://user-images.githubusercontent.com/5327677/58973099-b8466500-87f1-11e9-94a2-7403e7627959.gif)

**Comment by abcfy2** [comment]
起初以为是窗口特效的问题，在真机环境关闭窗口特效还是不行。

在虚拟机倒是没问题，希望可以排查一下

**Comment by Iceyer** [comment]
执行下下面的命令试试

```
ps -ef|grep sync
```

**Comment by abcfy2** [comment]
```
$ ps -ef|grep sync
systemd+  2839     1  0 16:44 ?        00:00:00 /lib/systemd/systemd-timesyncd
root      5623     1  0 16:44 ?        00:00:00 /usr/lib/deepin-sync-daemon/deepin-sync-helper
fengyu   26838 26592  0 19:43 pts/0    00:00:00 grep --color=auto sync
```

**Comment by Iceyer** [comment]
手动执行下这个看看结果

/usr/lib/deepin-sync-daemon/deepin-sync-daemon

**Comment by abcfy2** [comment]
```
$ /usr/lib/deepin-sync-daemon/deepin-sync-daemon
[CRI] 2019/06/10 - 20:02:46 | main.go:33 | main | 000001 failed to get hardware info: open /sys/class/dmi/id/board_asset_tag: no such file or directory
```

**Comment by Iceyer** [comment]
@jouyouyun 和之前龙芯上类似的问题。

**Comment by jouyouyun** [comment]
@abcfy2 贴一下 `apt-cache policy deepin-sync-daemon` 的版本

**Comment by abcfy2** [comment]
```
$ apt-cache policy deepin-sync-daemon
deepin-sync-daemon:
  已安装：1.0.4-1+comsta
  候选： 1.0.4-1+comsta
  版本列表：
 *** 1.0.4-1+comsta 500
        500 http://packages.deepin.com/deepin lion/main amd64 Packages
        500 http://packages.deepin.com/deepin lion/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by jouyouyun** [comment]
> ```
> $ apt-cache policy deepin-sync-daemon
> deepin-sync-daemon:
>   已安装：1.0.4-1+comsta
>   候选： 1.0.4-1+comsta
>   版本列表：
>  *** 1.0.4-1+comsta 500
>         500 http://packages.deepin.com/deepin lion/main amd64 Packages
>         500 http://packages.deepin.com/deepin lion/main i386 Packages
>         100 /var/lib/dpkg/status
> ```

版本太旧，请等待更新

**Comment by abcfy2** [comment]
下一次软件仓库更新大概是什么时候呢？

**Comment by Iceyer** [comment]
@abcfy2 现在好了吗？

**Comment by abcfy2** [comment]
已经修复，多谢了。时间太久忘了这个issue了，我这就关掉，感谢deepin团队的辛劳
