### ISSUE TITLE
总是找不到，不知道是怎么回事

### ISSUE THREAD

**Issue by code-wangshuyi** [linuxdeepin/deepin-appstore#57]
settings.go:6:2: cannot find package "github.com/go-ini/ini" in any of:
	/usr/lib/go-1.10/src/github.com/go-ini/ini (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/github.com/go-ini/ini (from $GOPATH)
	/usr/share/gocode/src/github.com/go-ini/ini
deb.go:16:2: cannot find package "github.com/linuxdeepin/go-dbus-factory/com.deepin.lastore" in any of:
	/usr/lib/go-1.10/src/github.com/linuxdeepin/go-dbus-factory/com.deepin.lastore (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/github.com/linuxdeepin/go-dbus-factory/com.deepin.lastore (from $GOPATH)
	/usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/com.deepin.lastore
deb.go:17:2: cannot find package "github.com/linuxdeepin/go-dbus-factory/org.freedesktop.dbus" in any of:
	/usr/lib/go-1.10/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.dbus (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.dbus (from $GOPATH)
	/usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/org.freedesktop.dbus
deb.go:18:2: cannot find package "pkg.deepin.io/lib/dbus1" in any of:
	/usr/lib/go-1.10/src/pkg.deepin.io/lib/dbus1 (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/pkg.deepin.io/lib/dbus1 (from $GOPATH)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus1
deb.go:19:2: cannot find package "pkg.deepin.io/lib/dbusutil" in any of:
	/usr/lib/go-1.10/src/pkg.deepin.io/lib/dbusutil (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/pkg.deepin.io/lib/dbusutil (from $GOPATH)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbusutil
deb_job.go:11:2: cannot find package "pkg.deepin.io/lib/dbusutil/proxy" in any of:
	/usr/lib/go-1.10/src/pkg.deepin.io/lib/dbusutil/proxy (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/pkg.deepin.io/lib/dbusutil/proxy (from $GOPATH)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbusutil/proxy
main.go:9:2: cannot find package "pkg.deepin.io/lib/log" in any of:
	/usr/lib/go-1.10/src/pkg.deepin.io/lib/log (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/pkg.deepin.io/lib/log (from $GOPATH)
	/usr/share/gocode/src/pkg.deepin.io/lib/log
metadata_ifc.go:8:2: cannot find package "pkg.deepin.io/lib/utils" in any of:
	/usr/lib/go-1.10/src/pkg.deepin.io/lib/utils (from $GOROOT)
	/home/shuyi/deepin-appstore-5.2.9.1/src/daemon/vendor/src/pkg.deepin.io/lib/utils (from $GOPATH)
	/usr/share/gocode/src/pkg.deepin.io/lib/utils

**Comment by Iceyer** [comment]
golang-github-go-ini-ini-dev
装一下这个包
