### ISSUE TITLE
Deepin app store ... awfully slow ... in accurate installation status graphic !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-appstore#6]
Hi,

I often find Deepin store to be awfully slow or in accurate on its installation progress info/graphic ...

in the following snapshot you'll see the installations haven't even started (loaded) ...

![deepinscreenshot_20171201161155](https://user-images.githubusercontent.com/3283676/33479324-abb26e5c-d6b2-11e7-9717-d2a7481a72b2.png)

Where as the terminal works smooth ... 

![deepinscreenshot_20171201161124](https://user-images.githubusercontent.com/3283676/33479359-d2a9778a-d6b2-11e7-98f4-eb4ce99c4ef1.png)

Shouldnt the Deepin apstore too work as smoothly as a terminal installation ... with an equally accurate progress info/graphic ?

**Comment by aiamuzz** [comment]
in spite of the 'x' mark to stop an installation ... it does not close/end the installation underway ...

**Comment by Iceyer** [comment]
the new deepin store 5.0 has the process of software install.
