### ISSUE TITLE
Some apps won't download from store

### ISSUE THREAD

**Issue by DanyGee** [linuxdeepin/deepin-appstore#7]
I found three apps that cannot be downloaded from store (so far):
Driver Manager
Deepin Calculator
PromoDoneApp
All share common "Download size: Calculating...".
When trying to download them, appstore says "Error downloading <appname>".
Installing from Terminal says that the specific package was not found.
Mirror changed from default, to the fastest (NLUUG) in my region (Poland). Changing back to the default one does not help.
Reinstalling store files with...
sudo apt-get install --reinstall lastore-daemon deepin-appstore deepin-appstore-data
...still didn't help.
I'm out of ideas for now :(

My sources list:
#Generated by deepin-installer
deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
#deb-src http://packages.deepin.com/deepin panda main contrib non-free
deb http://download.onlyoffice.com/repo/debian squeeze main

sudo apt-get update
Stary:1 http://download.onlyoffice.com/repo/debian squeeze InRelease
Stary:2 http://repository.spotify.com stable InRelease                                                        
Stary:3 https://repo.skype.com/deb stable InRelease                                
Stary:4 https://repo.skype.com/deb unstable InRelease                            
Stary:5 https://deb.opera.com/opera-stable stable InRelease                      
Stary:6 http://packages.deepin.com/deepin panda InRelease
Czytanie list pakietów... Gotowe

Apps that cant be downloaded...
![zrzut ekranu deepin_deepin-appstore_20171206134545](https://user-images.githubusercontent.com/26818551/33936668-964098da-e000-11e7-8683-5f4ae3973d13.png)
![zrzut ekranu deepin_deepin-appstore_20171206134628](https://user-images.githubusercontent.com/26818551/33936669-9660cf92-e000-11e7-9828-54b1b0e04488.png)
And here is an example of a downloadable app...
![zrzut ekranu deepin_deepin-appstore_20171206135217](https://user-images.githubusercontent.com/26818551/33936670-967f2f6e-e000-11e7-9b63-2b6638c04eef.png)

**Comment by munmaya** [comment]
i can't install app from deepin store.

**Comment by Iceyer** [comment]
Please try Deepin Store 5.0, it would be fixed.
