### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Synk0** [linuxdeepin/deepin-appstore#8]
The first problem is that when the images are being downloaded it shows what is behind (another program or the desktop)
![image](https://user-images.githubusercontent.com/6701156/35396494-101d9afa-01d4-11e8-80a1-d4d215eb2214.png)

Another problem is the magnifying glass and the text
![image](https://user-images.githubusercontent.com/6701156/35396606-5235d222-01d4-11e8-9d5e-60e10f0909ae.png)

**Comment by aiamuzz** [comment]
yup ... i confirm this behavior ... its always been like that from quite some time now !!!
overall experience of the Deepin Store is 'slow and laggy' ... in loading the snapshots as well as downloading/installing apps from the store ... most of the times i have cancelled the ongoing downloads at the store and installing the apps from the terminal which is faaar more quicker in downloading & installing apps ... provided the package name is easy to locate as the terminal requires the package name.

**Comment by Iceyer** [comment]
Please try Deepin Store 5.0, it would be fixed.
